### PR TITLE
Fix a path in unit tests

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
Fix the path in the unit test.

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
Testing this configuration would require enabling this repo on Travis CI. @rnorth could you please enable it (probably, somewhere around https://travis-ci.com/rnorth/mkdocs-codeinclude-plugin)?

**Comment by dmitry-timofeev** [comment]
Travis successfully built it in the fork: https://travis-ci.com/exonum/mkdocs-codeinclude-plugin/builds/149010227

**Comment by rnorth** [comment]
I think I'd prefer to use GitHub Actions actually. We're in the process of moving Testcontainers off Travis to GHA, and I'd prefer not to add a new dependency on Travis...

**Comment by dmitry-timofeev** [comment]
Ok, I removed the Travis CI and kept only the fix for the path.

**Comment by rnorth** [comment]
Thanks for this - and I'm very sorry for the _insane_ amount of time that I've not been paying attention to this repository.

Will merge.

**Comment by dmitry-timofeev** [comment]
Hi, no problem, thanks a lot for taking a look!

**Pull request merged**
